/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./../components/Content.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NSpin: typeof import('naive-ui')['NSpin']
  }
}
